name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for helping us evolve and fix our issues'' Thanks a bunch for opening your first issue! 🙏'
        pr-message: 'Please make it a beatiful code! And make us proud!! :)'' Thanks a lot for making your first pull request'
